-- KRI monthly submissions: one row per KRI per reporting month per entity.
-- This replaces the wide, repeating "month" columns + adjoining "Remarks for Amber and
-- Red" columns on the right-hand side of the "KRIs" sheet (12 monthly value columns +
-- 4 quarterly remarks columns per KRI, growing every year). Storing period as a single
-- DATE column (first day of the reporting month) instead of one column per month is
-- what makes this dashboardable and avoids the sheet ever needing new columns added.
--
-- Renamed from the working name "kri_dept_logs" -> kri_monthly_submissions, to make the
-- monthly intake/workflow nature of the table explicit.
CREATE TABLE IF NOT EXISTS dg_dev.sandbox.kri_monthly_submissions (
    submission_id        STRING NOT NULL COMMENT 'Surrogate key (UUID), generated by the app.',
    kri_id                BIGINT NOT NULL COMMENT 'References kri_catalog.kri_id.',
    reporting_period     DATE NOT NULL COMMENT 'First day of the reporting month, e.g. 2026-03-01.',
    actual_value_text    STRING COMMENT 'Actual value as submitted, verbatim. Kept as text because several KRIs report narrative status (e.g. "On-time") rather than a number.',
    actual_value_numeric DOUBLE COMMENT 'Parsed numeric value when actual_value_text is numeric/percentage, used for charting and aggregation. NULL for narrative KRIs.',
    rag_status            STRING NOT NULL COMMENT 'Green, Amber, or Red vs. the KRI thresholds at time of submission. See kri_lookup_values(rag_status).',
    remarks               STRING COMMENT 'Cause, action items, and target date narrative. Required in practice whenever rag_status is Amber or Red.',
    workflow_status       STRING NOT NULL COMMENT 'Draft, Submitted, Approved, or Rejected. See kri_lookup_values(workflow_status). Always set explicitly by the app (Submitted on insert).',
    submitted_by         STRING NOT NULL COMMENT 'Email/user id of the department submitter.',
    submitted_at         TIMESTAMP NOT NULL,
    approved_by           STRING COMMENT 'Email/user id of the Risk reviewer, once approved.',
    approved_at           TIMESTAMP,
    updated_by            STRING,
    updated_at            TIMESTAMP,
    CONSTRAINT kri_monthly_submissions_pk PRIMARY KEY (submission_id),
    CONSTRAINT kri_monthly_submissions_fk_kri FOREIGN KEY (kri_id) REFERENCES dg_dev.sandbox.kri_catalog (kri_id)
)
USING DELTA
COMMENT 'Fact table: one row per KRI per reporting month. App enforces one submission per (kri_id, reporting_period) via MERGE upsert; Delta does not enforce UNIQUE constraints.'
TBLPROPERTIES (delta.enableChangeDataFeed = true);
